// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GenerateProjectFilesUE
{
    internal sealed partial class Vsix
    {
        public const string Id = "GenerateProjectFilesUE.9cfd5622-a88d-4f81-8773-eba67948ef19";
        public const string Name = "GenerateProjectFilesUE";
        public const string Description = @"Adds a (Generate Project Files) command to .uproject file context";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "AgitoReiKen";
        public const string Tags = "unreal, unreal engine, ue, ue4 ,ue5, engine, generate, project, files";
    }
}
