// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnrealProjectRegenerator
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string UIContextSupportedFilesString = "d18bc1eb-721e-40cb-b7af-66aa7304123e";
        public static Guid UIContextSupportedFiles = new Guid(UIContextSupportedFilesString);

        public const string UnrealProjectRegeneratorString = "cd9f8b51-b49d-4ffc-9f5b-4f4f54d55ce7";
        public static Guid UnrealProjectRegenerator = new Guid(UnrealProjectRegeneratorString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0002;
        public const int MyCommandIcon = 0x0001;
        public const int MyCommand = 0x0100;
    }
}